"TMP_DATA_DIR": "data/rakuren_ja/" #directory put temporary data
"DATA_FOLDER": "data/mydata" #output directory
"DATA_DOMAIN_A": "domain_a.txt" #input filename
"DATA_DOMAIN_B": "domain_b.txt" #input filename
"TMP_DATA": "rakuten_reviews.json" #temporary filename
"TRAIN_TYPE": 0
"TEST_TYPE": 1
"VALIDATION_TYPE": 2
"POSITIVE_FILE_EXTENSION": ".pos"
"NEGATIVE_FILE_EXTENSION": ".neg"
"DATASET_TYPES": ""
"STARS_FIELD": "score"
"TEXT_FIELD": "review"
"DATASET_TYPES":
  "TRAIN_TYPE": "train"
  "TEST_TYPE": "test"
  "VALIDATION_TYPE": "valid"
"SCORE":
  "DOMAIN_A": 1
  "DOMAIN_B": 0
"POSITIVE_REVIEW_STARS_LIMIT": 5
"NEGATIVE_REVIEW_STARS_LIMIT": 1
"NUM_OF_SENTENCES_LIMIT": 10
"MIN_NUM_OF_WORDS_LIMIT": 2
"MAX_NUM_OF_WORDS_LIMIT": 25
"TEST_SIZE": 0.2
"VALIDATION_SIZE": 0.2

